### ISSUE TITLE
[FR] Transforming one keystroke into another

### ISSUE THREAD

**Issue by claudio-salvio** [guilryder/clavier-plus#20]
Hello @guilryder 

I think it would be very useful to have the possibility to define a rule that allows to capture a keystroke in a certain context and transform it into another one.

For example if the user press *F1* when CAPS LOCK is ON, Clavier+ captures the *F1* keystroke and generates a *F13* keystroke.

Specifically I think it would be to introduce a *new Keystroke action* (aditional to *Program*, *App* and *Special Character*) that is to capture a keystroke and generate another one.

Greetings,
Claudio

**Comment by claudio-salvio** [comment]
> Do this with _Write Text_ then [_Simulate Keystroke_](https://gryder.org/software/clavier-plus/documentation#text-simulating-keystroke).

Hello @guilryder 
Thanks for your prompt reply.

I explored your proposal but it does not seem to be useful in my case.
My goal is to remap keys (for example the G1-G6) in certain conditions to others not existing on my keyboard (for example F13-F24).
I can't find how to do that from the Clavier+ gui.

Before exploring Clavier+ for this task I explored other alternatives.
Since I have a Corsair keyboard, one of them was the iCue.
With iCue I managed to remap the six G keys as F13, F14, F15, F16, F17 and F18.
My final goal was to map the remaining keys up to F36 using the toggle keys (CAPS LOCK, NUM LOCK, SCROLL LOCK).

Unfortunately at Corsair they seem to be uninterested in helping users who use their products for work and not for gaming.
For more info about this see: [Using a combination or sequence of one of the G-keys plus another key](https://forum.corsair.com/forums/topic/170049-using-a-combination-or-sequence-of-one-of-the-g-keys-plus-another-key/) and [Remapping keys only when a toggling lock key (bloq, caps or scroll) is in a certain state](https://forum.corsair.com/forums/topic/176224-remapping-keys-only-when-a-toggling-lock-key-bloq-caps-or-scroll-is-in-a-certain-state/#comment-1011813)

Please let me know if you can think of any other suggestions to achieve this goal.

Regards,
Claudio Salvio

**Comment by guilryder** [comment]
Clavier+ supports only standard Windows keys: most but not all keys in [this list](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes). I've never heard of G1-G6 keys before, they don't seem standard. I guess that iCue uses a custom keyboard driver.

F13-F24 are standard so Clavier+ should be able to capture and simulate them. F25 and beyond are not standard.

See the [documentation](https://gryder.org/software/clavier-plus/documentation#add) for how to create shortcuts.

Closing this FR because Clavier+ already supports keystroke remapping (with limitations).
